# ===================================================================
# Configuration.
#
# This configuration will be overridden by the BACKEND_ENV you use,
# for example application-dev.yml if you use the "dev" profile.
#
# More information on profiles: https://www.jhipster.tech/profiles/
# More information on configuration properties: https://www.jhipster.tech/common-application-properties/
# ===================================================================

# ===================================================================
# Standard app properties.
# ===================================================================

consul:
  enabled: false # Default, can be overridden by environment-specific configs
  host: consul.appf4s.io.vn
  port: 443
  scheme: https
  prefer-ip-address: true
  service-name: gateway
  service-id: gateway:${random.value}
  health-check-interval: 10s
  health-check-timeout: 5s
  health-check-deregister-critical-service-after: 30s
  metadata-map:
    zone: primary # This is needed for the load balancer
    version: #project.version#
    git-version: ${git.commit.id.describe:}
    git-commit: ${git.commit.id.abbrev:}
    git-branch: ${git.branch:}

vault:
  enabled: true
  uri: http://appf4s.io.vn:8200
  token: ${VAULT_TOKEN}
  scheme: http
  kv:
    enabled: true
    backend: secret
    application-name: common-kafka
  # Import infrastructure secrets
  configuration:
    infrastructure: secret/infrastructure
  service-registration:
    enabled: true
    service-name: gateway
    service-id: gateway:${random.value}

server:
  port: 8080

mail:
  host: localhost
  port: 25
  username:
  password:

# ===================================================================
# JHipster specific properties
# ===================================================================

jhipster:
  clientApp:
    name: 'gateway'
  registry:
    password: admin
  security:
    session:
      secret: 'gateway session secret'
    oauth2:
      client:
        provider:
          oidc:
            issuer-uri: https://keycloak.appf4s.io.vn/realms/jhipster
        registration:
          oidc:
            client-id: web_app
            client-secret: 0TnpRknqjQYngbnbRW7hKECA8TbR4D7V
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret:
  mail:
    from: gateway@localhost
  swagger:
    default-include-pattern: /api/.*
    title: gateway API
    description: gateway API documentation
    version: 0.0.1
    terms-of-service-url:
    contact-name:
    contact-url:
    contact-email:
    license:
    license-url:
    path: /api/v3/api-docs

cloud:
  config:
    enabled: false
    uri: https://consul.appf4s.io.vn:443/v1/kv
    name: gateway
    profile: prod
    label: master
# ===================================================================
# Application specific properties
# Add your own application properties here, see the ApplicationProperties class
# to have type-safe configuration, like in the JHipsterProperties above
#
# More documentation is available at:
# https://www.jhipster.tech/common-application-properties/
# ===================================================================

# application:
