# ===================================================================
# Configuration for the "dev" profile.
#
# This configuration overrides the application.yml file.
#
# More information on profiles: https://www.jhipster.tech/profiles/
# More information on configuration properties: https://www.jhipster.tech/common-application-properties/
# ===================================================================

# ===================================================================
# Environment-specific overrides
# ===================================================================

# Override vault token for development
vault:
  token: ${VAULT_TOKEN:f4security}
  service-registration:
    enabled: false

# Development-specific mail base URL
jhipster:
  mail:
    base-url: http://127.0.0.1:8082
# ===================================================================
# Application specific properties
# Add your own application properties here, see the ApplicationProperties class
# to have type-safe configuration, like in the JHipsterProperties above
#
# More documentation is available at:
# https://www.jhipster.tech/common-application-properties/
# ===================================================================

# application:
